server:
  port: 8889
spring:
  # 配置mysql数据库
  datasource:
    url: jdbc:mysql://localhost:3406/vblog&autoReconnect=true&failOverReadOnly=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ${MYSQL_ROOT_PASSWORD}
  # 配置缓存
  cache:
    redis:
      time-to-live: 1d
file:
  upload:
    path: /projects/public/data/uploads/  #文件上传目标路径
    baseUrl: http://localhost/uploads/
